<%@ Page Language="vb" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script runat="server">

    Sub frmMovie_ItemInserted(sender As object, e As DetailsViewInsertedEventArgs)
        grdMovies.DataBind()
    End Sub
</script>

<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title>Edit LinqDataSource</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
    <asp:DetailsView
        id="frmMovie"
        DataSourceID="srcMovies"
        DefaultMode="Insert"
        AutoGenerateRows="false"
        AutoGenerateInsertButton="true"
        Runat="server" OnItemInserted="frmMovie_ItemInserted">
        <Fields>
        <asp:BoundField DataField="Title" HeaderText="Title" />
        <asp:BoundField DataField="Director" HeaderText="Director" />
        <asp:BoundField DataField="DateReleased" HeaderText="Date Released" />
        </Fields>
    </asp:DetailsView>    
    
    <br /><br />
    
    <asp:GridView
        id="grdMovies"
        DataKeyNames="Id"
        DataSourceID="srcMovies"
        AllowPaging="true"
        PageSize="5"
        AutoGenerateEditButton="true"
        AutoGenerateDeleteButton="true"
        Runat="server" />
    
    <asp:LinqDataSource
        id="srcMovies"
        ContextTypeName="MyDatabaseDataContext"
        TableName="Movies"
        OrderBy="Id descending"
        EnableInsert="true"
        EnableUpdate="true"
        EnableDelete="true"
        AutoPage="true"
        Runat="server" />
    
    </div>
    </form>
</body>
</html>
